### ISSUE TITLE
problem with function to enable if @ngx-translate

### ISSUE THREAD

**Issue by codewise-nicolas** [chr33z/vscode-lingua#26]
Im trying out the plugin but found that the function
`async function isNgxTranslateProject(): Promise<boolean> {
    const isAngular = await workspace.findFiles('**/angular.json', `**/node_modules/**`);
    const hasNgxTranslateModule = await workspace.findFiles('**/node_modules/**/ngx-translate*');
    return isAngular.length > 0 && hasNgxTranslateModule.length > 0;
}`

is too restrictive in how it chooses to enable the plugin.

For example, in my case, the module's folder is "@ngx-translate" which fails the above check.
Also, my workspace is open 1 level higher than the angular.json file so it also doesnt get enabled.

Ideally augment the function above to
- check for angular.json at any depth (all the project maybe?)
- also check for @ngx-translate

Ive modified it to always return true for my local copy to test with. Im liking the plugin very much so far, specially the inline key=>translation in light blue is very helpful. thanks.

**Comment by chr33z** [comment]
Thanks, I will look into it!

**Comment by codewise-nicolas** [comment]
Let me know if i can be of any help with ideas or testing.

**Comment by chr33z** [comment]
Thanks for providing feedback. I'm glad you like my plugin and I#m happy to add useful features (and fixing bugs of course)

1d617e9e0267745f87e5e46a7f55bfd57eab0d4d
