### ISSUE TITLE
[Feature] Sir, "flat" format please !

### ISSUE THREAD

**Issue by ocoka** [chr33z/vscode-lingua#36]
Hi, thanks for that extension, I've tryied all other that is present in vscode repo, you are the :1st_place_medal:, but, could you please add ability to use "flat" format keys in JSON for translation generation ?!

**Comment by ocoka** [comment]
Or add symbols,
:
/
>
as allowed for usage in key 
))
https://github.com/chr33z/vscode-lingua/blob/1c56e2d4ef099a395a449a847eb400ce8b3cb8c0/src/translation/translation-utils.ts#L3

**Comment by chr33z** [comment]
Hi there! I'm glad you like it :) Can you please give an example of "flat" format keys, so I get your concept?

**Comment by ocoka** [comment]
Yep, here it is, that's how we organize it:
![image](https://user-images.githubusercontent.com/8239290/82869913-be1fe380-9f37-11ea-89a7-d30d49292d9c.png)
We think that "flat" format is more convinient when do searching and refactoring,
and of course we understand that istead 'dot' we can use something other symbol

**Comment by chr33z** [comment]
I agree, refactoring is a pain in the ass! I'm still thinking about a good solution for it.

But supporting flat translations keys should be no problem. I will have a look!

**Comment by chr33z** [comment]
@ocoka 
I just run some tests to see whats happening with flat translation keys. They already work for translations but all the helper command like "Create Translation" just work for a nested hierarchy.

I guess I will add a flag in the settings where you can chose to use nested or flat hierarchy for translation keys.

**Comment by ocoka** [comment]
@chr33z 
Hi, it will be cool, thanks a lot

**Comment by ocoka** [comment]
Hi again and thank you, for the that feature and for care to the user ))) 
![image](https://user-images.githubusercontent.com/8239290/83322627-fb4ee300-a261-11ea-84d3-6557932287c2.png)

**Comment by chr33z** [comment]
I'm glad you like it!
