### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by Snote100024** [chr33z/vscode-lingua#51]
Hello,

The extension is not working for me. I use the last version of vscode (1.49.3) and the version 0.8.2 of the extension.

On a [language].json file in the editor, I don't have "Set as language file" in the context menu.
Also when I try to execute a command of the extenstion (e.g. **Lingua: Select your default language**), I get an error message 
(**Command 'Lingua: Select your default language' resulted in an error (command 'lingua.selectDefaultLanguage' not found)**)

I hope you can fix it soon

**Comment by Snote100024** [comment]
I work on a project with an old version of Angular therefore there is no angular.json file.
So this is not a bug

**Comment by chr33z** [comment]
No worries. If there's anything more that is not working for you, let me know!
