### ISSUE TITLE
Adding a translation changes the indention in the json file to 2 spaces regardless of the original format

### ISSUE THREAD

**Issue by paul-h** [chr33z/vscode-lingua#67]
I prefer to use 4 space for indentation so all my translation json files are formatted that way.

If I add a new translation using Lingua the resulting translation json file gets converted to use 2 spaces.

Lingua should attempt to preserve the original spacing or use whatever the editor default has been set to or failing that have a setting to choose the default spacing to use.

I believe this is the line that needs changing to pass the correct number of spaces to JSON.stringify().
https://github.com/chr33z/vscode-lingua/blob/master/src/translation/commands/translation-command-helper.ts#L24

**Comment by chr33z** [comment]
Thank you for your suggestion! I implemented a setting where you can define the indentation that is used when writing json files.
