### ISSUE TITLE
[Feature request]: sort translations keys

### ISSUE THREAD

**Issue by rdhainaut** [chr33z/vscode-lingua#84]
Hi,

I've tested a lot of ngx Translate extensions in VS Code to help me improve my work with ngx Translate in Angular projects, and your extension is really great! Fluid and with many features to really improve the i18n experience of an Angular application!

One feature missing to be truly perfect is automatic sorting of translation keys.
Ideally, sorting should be triggered after creating/adding a new translation.
It could also be very handy to have a new lingua command to do this manually directly in the translation json files.

**Comment by chr33z** [comment]
Hey @rdhainaut! Great idea! This will be added in the next release
