### ISSUE TITLE
Toggle for Intellisense

### ISSUE THREAD

**Issue by alexei-petru** [chr33z/vscode-lingua#85]
# Issue
Suggestions everywhere.
## Possible Solution
Preferably
 * Commands for toogle extension intellisense

Not preferably but still a solution.
 * Option to disable extension intellisense
##  Detailed Description
I like this extension ,is very useful and thank you for it but, many time i find myself buried in sugestion that i dont even need there. Is it possible/hard to make an option to disable intellisense or maybe better a command that i can switch on and off the intellisense for the extension.
### Visual Issue representation
<img src='https://github.com/chr33z/vscode-lingua/assets/76633311/2aa9ddcc-1df7-4a0b-9e68-007fa51b6da5' width='700'>

**Comment by chr33z** [comment]
Thank you for the suggestion and sorry for the long delay! 

In the next release I improved the algorithm that decides when to use autocomplete for translations keys. You Example should not happen anymore.

The new rules state that autocomplete is only shown when there is a ' or " or ` before the word you are typing. This will at least prevent autocomplete from popping up in the middle of the line.

There is also an extension parameter that allows you to enable or disable autocomplete.
